version: "3.8"
services:
  jenkins-python-firefox-chromium-selenium:
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CHROME_BIN: /usr/bin/chromium
        FIREFOX_BIN: /usr/bin/firefox

volumes:
  jenkins_data:


# docker-compose up --build -d
# --build is used to build the image again if the Dockerfile is changed


# docker ps
# docker stop <container_id>
# docker rm <container_id>
# docker volume ls
# docker volume rm jenkins_jenkins_data
# docker-compose up --build 

#
# echo the current time to a file:
# date > time.txt

# echo $(date)  # prints the current date and time
# we need the brackets otherwise it will print the string "date"

# 



